// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"vue-admin/app/ui/admin/internal/biz"
	"vue-admin/app/ui/admin/internal/conf"
	"vue-admin/app/ui/admin/internal/data"
	"vue-admin/app/ui/admin/internal/server"
	"vue-admin/app/ui/admin/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, auth *conf.Auth, logger log.Logger) (*kratos.App, func(), error) {
	discovery := data.NewDiscovery(registry)
	clientConn := data.NewRbacServiceConn(auth, discovery)
	adminClient := data.NewRbacServiceAdminClient(clientConn)
	roleClient := data.NewRbacServiceRoleClient(clientConn)
	dataData, err := data.NewData(confData, logger, adminClient, roleClient)
	if err != nil {
		return nil, nil, err
	}
	adminRepo := data.NewAdminRepo(dataData, logger)
	adminUseCase := biz.NewAdminUseCase(adminRepo, logger)
	rbacAdmin := service.NewRbacAdmin(adminUseCase, logger)
	roleRepo := data.NewRoleRepo(dataData, logger)
	roleUseCase := biz.NewRoleUseCase(roleRepo, logger)
	rbacRole := service.NewRbacRole(roleUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, auth, rbacAdmin, rbacRole, logger)
	httpServer := server.NewHTTPServer(confServer, rbacAdmin, rbacRole, logger)
	registrar := data.NewRegistrar(registry)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
	}, nil
}
