// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"vue-admin/app/ui/admin/internal/biz"
	"vue-admin/app/ui/admin/internal/conf"
	"vue-admin/app/ui/admin/internal/data"
	"vue-admin/app/ui/admin/internal/server"
	"vue-admin/app/ui/admin/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, auth *conf.Auth, logger log.Logger) (*kratos.App, func(), error) {
	discovery := data.NewDiscovery(registry)
	rbacClient := data.NewRbacServiceClient(auth, discovery)
	dataData, err := data.NewData(confData, logger, rbacClient)
	if err != nil {
		return nil, nil, err
	}
	rbacRepo := data.NewRbacRepo(dataData, logger)
	rbacUseCase := biz.NewRbacUseCase(rbacRepo, logger)
	uiAdmin := service.NewUiAdmin(rbacUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, auth, uiAdmin, logger)
	httpServer := server.NewHTTPServer(confServer, uiAdmin, logger)
	registrar := data.NewRegistrar(registry)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
	}, nil
}
