// Code generated by ent, DO NOT EDIT.

package roleadmin

import (
	"vue-admin/app/rbac/service/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RoleAdmin {
	return predicate.RoleAdmin(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RoleAdmin {
	return predicate.RoleAdmin(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RoleAdmin {
	return predicate.RoleAdmin(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RoleAdmin {
	return predicate.RoleAdmin(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RoleAdmin {
	return predicate.RoleAdmin(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RoleAdmin {
	return predicate.RoleAdmin(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RoleAdmin {
	return predicate.RoleAdmin(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RoleAdmin {
	return predicate.RoleAdmin(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RoleAdmin {
	return predicate.RoleAdmin(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// RoleID applies equality check predicate on the "role_id" field. It's identical to RoleIDEQ.
func RoleID(v int) predicate.RoleAdmin {
	return predicate.RoleAdmin(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldRoleID), v))
	})
}

// AdminID applies equality check predicate on the "admin_id" field. It's identical to AdminIDEQ.
func AdminID(v int64) predicate.RoleAdmin {
	return predicate.RoleAdmin(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAdminID), v))
	})
}

// RoleIDEQ applies the EQ predicate on the "role_id" field.
func RoleIDEQ(v int) predicate.RoleAdmin {
	return predicate.RoleAdmin(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldRoleID), v))
	})
}

// RoleIDNEQ applies the NEQ predicate on the "role_id" field.
func RoleIDNEQ(v int) predicate.RoleAdmin {
	return predicate.RoleAdmin(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldRoleID), v))
	})
}

// RoleIDIn applies the In predicate on the "role_id" field.
func RoleIDIn(vs ...int) predicate.RoleAdmin {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RoleAdmin(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldRoleID), v...))
	})
}

// RoleIDNotIn applies the NotIn predicate on the "role_id" field.
func RoleIDNotIn(vs ...int) predicate.RoleAdmin {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RoleAdmin(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldRoleID), v...))
	})
}

// RoleIDGT applies the GT predicate on the "role_id" field.
func RoleIDGT(v int) predicate.RoleAdmin {
	return predicate.RoleAdmin(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldRoleID), v))
	})
}

// RoleIDGTE applies the GTE predicate on the "role_id" field.
func RoleIDGTE(v int) predicate.RoleAdmin {
	return predicate.RoleAdmin(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldRoleID), v))
	})
}

// RoleIDLT applies the LT predicate on the "role_id" field.
func RoleIDLT(v int) predicate.RoleAdmin {
	return predicate.RoleAdmin(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldRoleID), v))
	})
}

// RoleIDLTE applies the LTE predicate on the "role_id" field.
func RoleIDLTE(v int) predicate.RoleAdmin {
	return predicate.RoleAdmin(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldRoleID), v))
	})
}

// AdminIDEQ applies the EQ predicate on the "admin_id" field.
func AdminIDEQ(v int64) predicate.RoleAdmin {
	return predicate.RoleAdmin(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAdminID), v))
	})
}

// AdminIDNEQ applies the NEQ predicate on the "admin_id" field.
func AdminIDNEQ(v int64) predicate.RoleAdmin {
	return predicate.RoleAdmin(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldAdminID), v))
	})
}

// AdminIDIn applies the In predicate on the "admin_id" field.
func AdminIDIn(vs ...int64) predicate.RoleAdmin {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RoleAdmin(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldAdminID), v...))
	})
}

// AdminIDNotIn applies the NotIn predicate on the "admin_id" field.
func AdminIDNotIn(vs ...int64) predicate.RoleAdmin {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RoleAdmin(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldAdminID), v...))
	})
}

// AdminIDGT applies the GT predicate on the "admin_id" field.
func AdminIDGT(v int64) predicate.RoleAdmin {
	return predicate.RoleAdmin(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldAdminID), v))
	})
}

// AdminIDGTE applies the GTE predicate on the "admin_id" field.
func AdminIDGTE(v int64) predicate.RoleAdmin {
	return predicate.RoleAdmin(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldAdminID), v))
	})
}

// AdminIDLT applies the LT predicate on the "admin_id" field.
func AdminIDLT(v int64) predicate.RoleAdmin {
	return predicate.RoleAdmin(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldAdminID), v))
	})
}

// AdminIDLTE applies the LTE predicate on the "admin_id" field.
func AdminIDLTE(v int64) predicate.RoleAdmin {
	return predicate.RoleAdmin(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldAdminID), v))
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RoleAdmin) predicate.RoleAdmin {
	return predicate.RoleAdmin(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RoleAdmin) predicate.RoleAdmin {
	return predicate.RoleAdmin(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RoleAdmin) predicate.RoleAdmin {
	return predicate.RoleAdmin(func(s *sql.Selector) {
		p(s.Not())
	})
}
