// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"vue-admin/app/rbac/service/internal/data/ent/predicate"
	"vue-admin/app/rbac/service/internal/data/ent/roleadmin"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RoleAdminQuery is the builder for querying RoleAdmin entities.
type RoleAdminQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.RoleAdmin
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RoleAdminQuery builder.
func (raq *RoleAdminQuery) Where(ps ...predicate.RoleAdmin) *RoleAdminQuery {
	raq.predicates = append(raq.predicates, ps...)
	return raq
}

// Limit adds a limit step to the query.
func (raq *RoleAdminQuery) Limit(limit int) *RoleAdminQuery {
	raq.limit = &limit
	return raq
}

// Offset adds an offset step to the query.
func (raq *RoleAdminQuery) Offset(offset int) *RoleAdminQuery {
	raq.offset = &offset
	return raq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (raq *RoleAdminQuery) Unique(unique bool) *RoleAdminQuery {
	raq.unique = &unique
	return raq
}

// Order adds an order step to the query.
func (raq *RoleAdminQuery) Order(o ...OrderFunc) *RoleAdminQuery {
	raq.order = append(raq.order, o...)
	return raq
}

// First returns the first RoleAdmin entity from the query.
// Returns a *NotFoundError when no RoleAdmin was found.
func (raq *RoleAdminQuery) First(ctx context.Context) (*RoleAdmin, error) {
	nodes, err := raq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{roleadmin.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (raq *RoleAdminQuery) FirstX(ctx context.Context) *RoleAdmin {
	node, err := raq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RoleAdmin ID from the query.
// Returns a *NotFoundError when no RoleAdmin ID was found.
func (raq *RoleAdminQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = raq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{roleadmin.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (raq *RoleAdminQuery) FirstIDX(ctx context.Context) int {
	id, err := raq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RoleAdmin entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RoleAdmin entity is found.
// Returns a *NotFoundError when no RoleAdmin entities are found.
func (raq *RoleAdminQuery) Only(ctx context.Context) (*RoleAdmin, error) {
	nodes, err := raq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{roleadmin.Label}
	default:
		return nil, &NotSingularError{roleadmin.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (raq *RoleAdminQuery) OnlyX(ctx context.Context) *RoleAdmin {
	node, err := raq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RoleAdmin ID in the query.
// Returns a *NotSingularError when more than one RoleAdmin ID is found.
// Returns a *NotFoundError when no entities are found.
func (raq *RoleAdminQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = raq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{roleadmin.Label}
	default:
		err = &NotSingularError{roleadmin.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (raq *RoleAdminQuery) OnlyIDX(ctx context.Context) int {
	id, err := raq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RoleAdmins.
func (raq *RoleAdminQuery) All(ctx context.Context) ([]*RoleAdmin, error) {
	if err := raq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return raq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (raq *RoleAdminQuery) AllX(ctx context.Context) []*RoleAdmin {
	nodes, err := raq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RoleAdmin IDs.
func (raq *RoleAdminQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := raq.Select(roleadmin.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (raq *RoleAdminQuery) IDsX(ctx context.Context) []int {
	ids, err := raq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (raq *RoleAdminQuery) Count(ctx context.Context) (int, error) {
	if err := raq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return raq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (raq *RoleAdminQuery) CountX(ctx context.Context) int {
	count, err := raq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (raq *RoleAdminQuery) Exist(ctx context.Context) (bool, error) {
	if err := raq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return raq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (raq *RoleAdminQuery) ExistX(ctx context.Context) bool {
	exist, err := raq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RoleAdminQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (raq *RoleAdminQuery) Clone() *RoleAdminQuery {
	if raq == nil {
		return nil
	}
	return &RoleAdminQuery{
		config:     raq.config,
		limit:      raq.limit,
		offset:     raq.offset,
		order:      append([]OrderFunc{}, raq.order...),
		predicates: append([]predicate.RoleAdmin{}, raq.predicates...),
		// clone intermediate query.
		sql:    raq.sql.Clone(),
		path:   raq.path,
		unique: raq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		RoleID int `json:"role_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RoleAdmin.Query().
//		GroupBy(roleadmin.FieldRoleID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (raq *RoleAdminQuery) GroupBy(field string, fields ...string) *RoleAdminGroupBy {
	grbuild := &RoleAdminGroupBy{config: raq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := raq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return raq.sqlQuery(ctx), nil
	}
	grbuild.label = roleadmin.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		RoleID int `json:"role_id,omitempty"`
//	}
//
//	client.RoleAdmin.Query().
//		Select(roleadmin.FieldRoleID).
//		Scan(ctx, &v)
//
func (raq *RoleAdminQuery) Select(fields ...string) *RoleAdminSelect {
	raq.fields = append(raq.fields, fields...)
	selbuild := &RoleAdminSelect{RoleAdminQuery: raq}
	selbuild.label = roleadmin.Label
	selbuild.flds, selbuild.scan = &raq.fields, selbuild.Scan
	return selbuild
}

func (raq *RoleAdminQuery) prepareQuery(ctx context.Context) error {
	for _, f := range raq.fields {
		if !roleadmin.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if raq.path != nil {
		prev, err := raq.path(ctx)
		if err != nil {
			return err
		}
		raq.sql = prev
	}
	return nil
}

func (raq *RoleAdminQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RoleAdmin, error) {
	var (
		nodes = []*RoleAdmin{}
		_spec = raq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*RoleAdmin).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &RoleAdmin{config: raq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, raq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (raq *RoleAdminQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := raq.querySpec()
	_spec.Node.Columns = raq.fields
	if len(raq.fields) > 0 {
		_spec.Unique = raq.unique != nil && *raq.unique
	}
	return sqlgraph.CountNodes(ctx, raq.driver, _spec)
}

func (raq *RoleAdminQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := raq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (raq *RoleAdminQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   roleadmin.Table,
			Columns: roleadmin.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: roleadmin.FieldID,
			},
		},
		From:   raq.sql,
		Unique: true,
	}
	if unique := raq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := raq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, roleadmin.FieldID)
		for i := range fields {
			if fields[i] != roleadmin.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := raq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := raq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := raq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := raq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (raq *RoleAdminQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(raq.driver.Dialect())
	t1 := builder.Table(roleadmin.Table)
	columns := raq.fields
	if len(columns) == 0 {
		columns = roleadmin.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if raq.sql != nil {
		selector = raq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if raq.unique != nil && *raq.unique {
		selector.Distinct()
	}
	for _, p := range raq.predicates {
		p(selector)
	}
	for _, p := range raq.order {
		p(selector)
	}
	if offset := raq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := raq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RoleAdminGroupBy is the group-by builder for RoleAdmin entities.
type RoleAdminGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ragb *RoleAdminGroupBy) Aggregate(fns ...AggregateFunc) *RoleAdminGroupBy {
	ragb.fns = append(ragb.fns, fns...)
	return ragb
}

// Scan applies the group-by query and scans the result into the given value.
func (ragb *RoleAdminGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := ragb.path(ctx)
	if err != nil {
		return err
	}
	ragb.sql = query
	return ragb.sqlScan(ctx, v)
}

func (ragb *RoleAdminGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range ragb.fields {
		if !roleadmin.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := ragb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ragb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ragb *RoleAdminGroupBy) sqlQuery() *sql.Selector {
	selector := ragb.sql.Select()
	aggregation := make([]string, 0, len(ragb.fns))
	for _, fn := range ragb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(ragb.fields)+len(ragb.fns))
		for _, f := range ragb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(ragb.fields...)...)
}

// RoleAdminSelect is the builder for selecting fields of RoleAdmin entities.
type RoleAdminSelect struct {
	*RoleAdminQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ras *RoleAdminSelect) Scan(ctx context.Context, v interface{}) error {
	if err := ras.prepareQuery(ctx); err != nil {
		return err
	}
	ras.sql = ras.RoleAdminQuery.sqlQuery(ctx)
	return ras.sqlScan(ctx, v)
}

func (ras *RoleAdminSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ras.sql.Query()
	if err := ras.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
