// Code generated by ent, DO NOT EDIT.

package permission

const (
	// Label holds the string label denoting the permission type in the database.
	Label = "permission"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRoleID holds the string denoting the role_id field in the database.
	FieldRoleID = "role_id"
	// FieldPermissionRuleID holds the string denoting the permission_rule_id field in the database.
	FieldPermissionRuleID = "permission_rule_id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// Table holds the table name of the permission in the database.
	Table = "permission"
)

// Columns holds all SQL columns for permission fields.
var Columns = []string{
	FieldID,
	FieldRoleID,
	FieldPermissionRuleID,
	FieldType,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
