// Code generated by ent, DO NOT EDIT.

package permissionrule

const (
	// Label holds the string label denoting the permissionrule type in the database.
	Label = "permission_rule"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPid holds the string denoting the pid field in the database.
	FieldPid = "pid"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCondition holds the string denoting the condition field in the database.
	FieldCondition = "condition"
	// FieldSort holds the string denoting the sort field in the database.
	FieldSort = "sort"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// Table holds the table name of the permissionrule in the database.
	Table = "permission_rules"
)

// Columns holds all SQL columns for permissionrule fields.
var Columns = []string{
	FieldID,
	FieldPid,
	FieldName,
	FieldTitle,
	FieldStatus,
	FieldCondition,
	FieldSort,
	FieldCreateTime,
	FieldUpdateTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
