// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.4.1
// - protoc             v3.21.5
// source: v1/rbac_role.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationRbacRoleCreateRbacRole = "/api.ui.admin.v1.RbacRole/CreateRbacRole"

type RbacRoleHTTPServer interface {
	CreateRbacRole(context.Context, *CreateRbacRoleRequest) (*CreateRbacRoleReply, error)
}

func RegisterRbacRoleHTTPServer(s *http.Server, srv RbacRoleHTTPServer) {
	r := s.Route("/")
	r.POST("/admin/v1/rbac/role", _RbacRole_CreateRbacRole0_HTTP_Handler(srv))
}

func _RbacRole_CreateRbacRole0_HTTP_Handler(srv RbacRoleHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateRbacRoleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRbacRoleCreateRbacRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateRbacRole(ctx, req.(*CreateRbacRoleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateRbacRoleReply)
		return ctx.Result(200, reply)
	}
}

type RbacRoleHTTPClient interface {
	CreateRbacRole(ctx context.Context, req *CreateRbacRoleRequest, opts ...http.CallOption) (rsp *CreateRbacRoleReply, err error)
}

type RbacRoleHTTPClientImpl struct {
	cc *http.Client
}

func NewRbacRoleHTTPClient(client *http.Client) RbacRoleHTTPClient {
	return &RbacRoleHTTPClientImpl{client}
}

func (c *RbacRoleHTTPClientImpl) CreateRbacRole(ctx context.Context, in *CreateRbacRoleRequest, opts ...http.CallOption) (*CreateRbacRoleReply, error) {
	var out CreateRbacRoleReply
	pattern := "/admin/v1/rbac/role"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRbacRoleCreateRbacRole))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
