// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.4.1
// - protoc             v3.21.5
// source: v1/rbac_admin.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationRbacAdminCreateRbacAdmin = "/api.ui.admin.v1.RbacAdmin/CreateRbacAdmin"

type RbacAdminHTTPServer interface {
	CreateRbacAdmin(context.Context, *CreateRbacAdminRequest) (*CreateRbacAdminReply, error)
}

func RegisterRbacAdminHTTPServer(s *http.Server, srv RbacAdminHTTPServer) {
	r := s.Route("/")
	r.POST("/admin/v1/rbac/admin", _RbacAdmin_CreateRbacAdmin0_HTTP_Handler(srv))
}

func _RbacAdmin_CreateRbacAdmin0_HTTP_Handler(srv RbacAdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateRbacAdminRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRbacAdminCreateRbacAdmin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateRbacAdmin(ctx, req.(*CreateRbacAdminRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateRbacAdminReply)
		return ctx.Result(200, reply)
	}
}

type RbacAdminHTTPClient interface {
	CreateRbacAdmin(ctx context.Context, req *CreateRbacAdminRequest, opts ...http.CallOption) (rsp *CreateRbacAdminReply, err error)
}

type RbacAdminHTTPClientImpl struct {
	cc *http.Client
}

func NewRbacAdminHTTPClient(client *http.Client) RbacAdminHTTPClient {
	return &RbacAdminHTTPClientImpl{client}
}

func (c *RbacAdminHTTPClientImpl) CreateRbacAdmin(ctx context.Context, in *CreateRbacAdminRequest, opts ...http.CallOption) (*CreateRbacAdminReply, error) {
	var out CreateRbacAdminReply
	pattern := "/admin/v1/rbac/admin"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRbacAdminCreateRbacAdmin))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
